# Website settings
url: "https://www.jhsvendsen.com"

# Internal nav
nav:
  main:
    writing: "/writing"
    videos: "/vidoes"
    research: "/projects"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "Johan Hentze Svendsen"
description: "The home page of Johan Hentze Svendsen, MSc Motorsport Engineering"
thumbnail_path: "profile-photos/johan.jpg"

# URLs
contact_urls:
  linkedin:
    url: "https://www.linkedin.com/in/johanhentzesvendsen"
    label: "LinkedIn"
    icon: "linkedin-square"
  facebook:
    url: "https://www.facebook.com/johan.hentze.5"
    label: "Facebook"
    icon: "facebook-square"
  github:
    url: "https://github.com/jhsvendsen"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:j.hentze.svendsen@gmail.com"
    label: "Email"
    value: "j.hentze.svendsen@gmail.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'Europe/Berlin'
repository: brikis98/yevgeniy-brikman-homepage

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
